Initial commit of syntax highlighting VS Code extension
rticommunity/vscode-omg-idl pull request #1
Opened 2019-11-13 21:28 UTC by rosemwahlin

Initial commit of syntax highlighting.

README points to a file in the rticommunity repo that won't be there until we merge.  (If the URL is wrong, it might need to be update)

2019-11-14 09:46 UTC, fgaranda requested changes

2019-11-14 09:46 UTC, fgaranda commented on package.json
> +    "version": "0.0.1",
Should this be version 1.0?

2019-11-14 09:46 UTC, fgaranda commented on syntaxes/omg.idl.tmLanguage.json
> +{
Could you use 4-spaces instead of tabs? The rest of documents are using that convention

2019-11-14 09:46 UTC, fgaranda commented on syntaxes/omg.idl.tmLanguage.json
> +				"match": "\\b(short)\\b"
This pattern should also match the new fixed-width integer notation defined in the Extended Types building block of IDL 4.2. That is, it should match both `short` and `int16`.

The same applies to the rest of signed and unsigned integer types:
- `unsigned short` - `uint16`
- `long` - `int32`
- `unsigned long` - `uint32`
- `long long` - `int64`
- `unsigned long long`  - `uint64`

2019-11-14 09:46 UTC, fgaranda commented on syntaxes/omg.idl.tmLanguage.json
> +			]
IDL 4.2 has introduced support for 8-bit integer values. They are definde in BNF as follows:
```
(208) <signed_tiny_int> ::= “int8”
(209) <unsigned_tiny_int> ::= “uint8”
```
Following your notation, you could add an include for `signed_tiny_int` under `signed_int` and `unsigned_tiny_int` under `unsigned_int`.

2019-11-14 09:46 UTC, fgaranda commented on syntaxes/omg.idl.tmLanguage.json
> +}
Add newline

2019-11-15 01:32 UTC, rosemwahlin commented
Issues should be fixed, including the ones visible in the test file you recommended.

2019-12-05 09:57 UTC, fgaranda approved these changes

2019-12-05 09:59 UTC, merged